name: Simple .NET CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

  test:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Run tests
        run: |
          dotnet test \
            --configuration Release \
            --logger "trx;LogFileName=test-results.trx" \
            --results-directory "artifacts/test-results"
      - name: Upload .trx
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: TestResults
          path: artifacts/test-results/**/*.trx

      - name: Test report
        uses: dorny/test-reporter@v2
        if: ${{ always() }}
        with:
          name: Tests
          path: artifacts/test-results/**/*.trx
          reporter: dotnet-trx
